// Generated by tools/gen_model_registry.py from models.yaml —
// do not edit by hand. Edit models.yaml and rerun the generator.
// (ADR-016: the app reads these constants; nothing parses YAML at runtime.)
package dev.breaker.shared.models

enum class ModelFamily {
    SHERPA_ONNX,
    WHISPER,
}

data class ModelEntry(
    val id: String,
    val family: ModelFamily,
    val url: String,
    val sha256: String,
    val sizeMb: Int,
    val licence: String,
    val hosted: Boolean,
)

object ModelRegistry {
    val SMALL: ModelEntry = ModelEntry(
        id = "small",
        family = ModelFamily.SHERPA_ONNX,
        url = "https://api.github.com/repos/k2-fsa/sherpa-onnx/releases/assets/191972150",
        sha256 = "b97e7ff75a27136f4dd33c99bb7d5f493094397501be4739578c6cd95ea7f422",
        sizeMb = 349,
        licence = "Apache-2.0",
        hosted = false,
    )

    val TINY: ModelEntry = ModelEntry(
        id = "tiny",
        family = ModelFamily.SHERPA_ONNX,
        url = "https://api.github.com/repos/k2-fsa/sherpa-onnx/releases/assets/143510207",
        sha256 = "9c559283e8498d3fe95913c79ca1cb454bb26281ac2b102b41306c7d752765d9",
        sizeMb = 122,
        licence = "Apache-2.0",
        hosted = false,
    )

    val BASE: ModelEntry = ModelEntry(
        id = "base",
        family = ModelFamily.WHISPER,
        url = "https://api.github.com/repos/k2-fsa/sherpa-onnx/releases/assets/196350763",
        sha256 = "475bc7052ce299c007f6d5d5407ba8601f819a2867f6eecee510ed17df581542",
        sizeMb = 199,
        licence = "MIT",
        hosted = false,
    )

    val MEDIUM: ModelEntry = ModelEntry(
        id = "medium",
        family = ModelFamily.WHISPER,
        url = "https://api.github.com/repos/k2-fsa/sherpa-onnx/releases/assets/179372814",
        sha256 = "73d95c169a410b5f23a79f8901374b26e0a16a09ea7f02b5e1db983f4cdfdd67",
        sizeMb = 1818,
        licence = "MIT",
        hosted = false,
    )

    val ALL: List<ModelEntry> = listOf(SMALL, TINY, BASE, MEDIUM)

    fun byId(id: String): ModelEntry? = ALL.firstOrNull { it.id == id }
}
