// Generated by tools/gen_model_registry.py from models.yaml —
// do not edit by hand. Edit models.yaml and rerun the generator.
// (ADR-016: the app reads these constants; nothing parses YAML at runtime.)
package dev.breaker.shared.models

enum class ModelFamily {
    SHERPA_ONNX,
    WHISPER,
}

data class ModelEntry(
    val id: String,
    val family: ModelFamily,
    val url: String,
    val sha256: String,
    val sizeMb: Int,
    val licence: String,
    val hosted: Boolean,
)

object ModelRegistry {
    val SMALL: ModelEntry = ModelEntry(
        id = "small",
        family = ModelFamily.SHERPA_ONNX,
        url = "https://api.github.com/repos/k2-fsa/sherpa-onnx/releases/assets/191972150",
        sha256 = "b97e7ff75a27136f4dd33c99bb7d5f493094397501be4739578c6cd95ea7f422",
        sizeMb = 349,
        licence = "Apache-2.0",
        hosted = false,
    )

    val ALL: List<ModelEntry> = listOf(SMALL)

    fun byId(id: String): ModelEntry? = ALL.firstOrNull { it.id == id }
}
