package dev.breaker.dictation.stt.ondevice

import dev.breaker.shared.models.ModelEntry
import dev.breaker.shared.models.ModelFamily
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.security.MessageDigest

/*
 * Fakes for the tests of the real model fetcher. Nothing here opens a socket, reads a clock
 * or waits: time is a number the streams advance, a cancel is a flag a stream flips. Each
 * counter has one writer (the fetcher's own thread) and is read afterwards, so volatile is enough.
 */

/** Addresses and sizes shared by the fetcher tests. */
internal object HttpFixtures {
    const val ASSET_URL = "https://api.github.com/repos/k2-fsa/sherpa-onnx/releases/assets/143510207"
    const val SECRET = "SECRETTOKEN"
    const val RELEASE_HOST = "release-assets.githubusercontent.com"
    const val RELEASE_URL = "https://release-assets.githubusercontent.com/github-production-release-asset/1/abc?sig=SECRETTOKEN"
    const val MIB = 1_048_576L

    /** The cap of an entry whose size is 1 MiB: two MiB. */
    const val CAP_1MB = 2_097_152L
}

/** A registry entry by hand. The default size of 1 MiB gives a cap of two MiB. */
internal fun testEntry(id: String = "tiny", sizeMb: Int = 1, url: String = HttpFixtures.ASSET_URL, sha256: String = "0".repeat(64)): ModelEntry =
    ModelEntry(id, ModelFamily.SHERPA_ONNX, url, sha256, sizeMb, "Apache-2.0", false)

/** Lower-case hex SHA-256 of [bytes], computed by the test itself. */
internal fun httpTestSha256Hex(bytes: ByteArray): String =
    MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

/** A checksum list with one line for [digest], in the shape the installer parses. */
internal fun httpTestChecksumList(digest: String): ByteArray = "model.archive\t$digest\n".toByteArray()

/** The names inside [dir], sorted; an absent directory reads as empty. */
internal fun stagedNames(dir: File): List<String> = dir.list()?.sorted() ?: emptyList()

/** A clock that only moves when a test or a stream moves it. */
internal class FakeClock(start: Long = 5_000L) {
    @Volatile var now: Long = start
    fun advance(millis: Long) { now += millis }
}

/** The cancel flag the fetcher polls; a test or a stream flips [on]. */
internal class CancelFlag {
    @Volatile var on: Boolean = false
    val check: () -> Boolean = { on }
}

/** Base of every body stream: counts reads, bytes and closes. Both read overloads go through [fill]. */
internal abstract class ProbeStream : InputStream() {
    @Volatile var closes: Int = 0
        private set

    /** How many read calls were made (either overload). */
    @Volatile var reads: Int = 0
        private set
    @Volatile var bytesServed: Long = 0L
        private set

    /** Fill up to [len] bytes at [off]; return the count, or -1 at the end. */
    protected abstract fun fill(b: ByteArray, off: Int, len: Int): Int

    final override fun read(b: ByteArray, off: Int, len: Int): Int {
        reads += 1
        if (len == 0) return 0
        val n = fill(b, off, len)
        if (n > 0) bytesServed += n.toLong()
        return n
    }

    final override fun read(): Int {
        val one = ByteArray(1)
        val n = read(one, 0, 1)
        return if (n <= 0) -1 else one[0].toInt() and 0xff
    }

    override fun close() { closes += 1 }
}

/** The bytes of [bytes], at most [chunk] per read, then the end. */
internal class BytesStream(private val bytes: ByteArray, private val chunk: Int = Int.MAX_VALUE) : ProbeStream() {
    private var pos = 0

    override fun fill(b: ByteArray, off: Int, len: Int): Int {
        if (pos >= bytes.size) return -1
        val n = minOf(len, chunk, bytes.size - pos)
        System.arraycopy(bytes, pos, b, off, n)
        pos += n
        return n
    }
}

/**
 * [total] generated bytes, at most [chunk] per read, then the end. [onRead] runs at the start of
 * every read call with the 1-based read number, so a test can act on read k and count what follows.
 */
internal open class SizedStream(total: Long, private val chunk: Int = Int.MAX_VALUE, private val onRead: (Int) -> Unit = {}) : ProbeStream() {
    private var remaining = total

    override fun fill(b: ByteArray, off: Int, len: Int): Int {
        onRead(reads)
        if (remaining <= 0L) return -1
        val n = minOf(len.toLong(), chunk.toLong(), remaining).toInt()
        java.util.Arrays.fill(b, off, off + n, 7.toByte())
        remaining -= n.toLong()
        return n
    }
}

/** A [SizedStream] of [total] bytes, 1000 per read, with a hook on every read. */
internal class HookStream(total: Long, chunk: Int = 1000, onRead: (Int) -> Unit) : SizedStream(total, chunk, onRead)

/** [afterBytes] bytes, then every read throws [error] (an IOException unless a test says otherwise). */
internal class FailingStream(private val afterBytes: Int, private val error: Throwable) : ProbeStream() {
    private var served = 0

    override fun fill(b: ByteArray, off: Int, len: Int): Int {
        if (served >= afterBytes) throw error
        val n = minOf(len, afterBytes - served)
        java.util.Arrays.fill(b, off, off + n, 7.toByte())
        served += n
        return n
    }
}

/** Never ends; a safety limit makes a fetcher that forgets its cap fail by name instead of running on. */
internal class EndlessStream(private val safetyLimit: Long = 16L * 1_048_576L) : SizedStream(Long.MAX_VALUE) {
    override fun fill(b: ByteArray, off: Int, len: Int): Int {
        if (bytesServed >= safetyLimit) throw AssertionError("an endless body was read past its safety limit of $safetyLimit bytes")
        return super.fill(b, off, len)
    }
}

/** A body that must not be read: any read throws an AssertionError that names [label]. */
internal class ThrowIfRead(private val label: String) : ProbeStream() {
    override fun fill(b: ByteArray, off: Int, len: Int): Int = throw AssertionError("$label was read")
}

/** Wraps [inner], counts how often it was closed, and closes it too. */
internal class CloseCounter(private val inner: InputStream) : ProbeStream() {
    override fun fill(b: ByteArray, off: Int, len: Int): Int = inner.read(b, off, len)

    override fun close() {
        super.close()
        inner.close()
    }
}

/** A scripted reply; the defaults describe a plain binary 200 with an empty body. */
internal fun reply(
    status: Int = 200,
    body: InputStream = BytesStream(ByteArray(0)),
    location: String? = null,
    contentLength: Long = -1L,
    contentType: String? = "application/octet-stream",
): HttpReply = HttpReply(status, location, contentType, contentLength, body)

/** A 200 whose body is [bytes]; the length is declared unless [declare] is false. */
internal fun okBytes(bytes: ByteArray, declare: Boolean = true): HttpReply =
    reply(200, BytesStream(bytes), contentLength = if (declare) bytes.size.toLong() else -1L)

/** A redirect reply with a counted empty body. */
internal fun redirectTo(location: String?, status: Int = 302): HttpReply =
    reply(status, CloseCounter(BytesStream(ByteArray(0))), location = location, contentType = null)

/** One thing the fake opener does for one request. */
internal typealias Step = () -> HttpReply

/** The opener answers with [reply]. */
internal fun serve(reply: HttpReply): Step = { reply }

/** The opener throws [error] (a connection problem, or something unexpected). */
internal fun failWith(error: Throwable): Step = { throw error }

/** What the opener was asked, copied at the moment of the call. */
internal class SeenRequest(val url: String, val headers: Map<String, String>, val connectTimeoutMillis: Int, val readTimeoutMillis: Int)

/**
 * Answers request n with step n. A request past the end of the script throws an AssertionError
 * (not an IOException). [onRequest] runs with the 0-based request number once it was recorded.
 */
internal class FakeOpener(private val script: List<Step>, private val onRequest: (Int) -> Unit = {}) : HttpOpener {
    constructor(vararg steps: Step) : this(steps.toList())

    private val seen = ArrayList<SeenRequest>()

    /** Every request made so far, in order. */
    val requests: List<SeenRequest> get() = seen

    override fun open(url: String, headers: Map<String, String>, connectTimeoutMillis: Int, readTimeoutMillis: Int): HttpReply {
        val index = seen.size
        seen.add(SeenRequest(url, headers.toMap(), connectTimeoutMillis, readTimeoutMillis))
        onRequest(index)
        if (index >= script.size) {
            val host = url.substringAfter("://").substringBefore('/').substringBefore('?')
            throw AssertionError("request ${index + 1} to $host was not scripted")
        }
        return script[index]()
    }
}

/** The injected openOutput: real files, recorded; [append] reopens a stale file without truncating it. */
internal class RecordingOutputs(private val append: Boolean = false) {
    private val opened = ArrayList<File>()

    @Volatile var bytesWritten: Long = 0L
    @Volatile var closes: Int = 0

    /** Every file the fetcher asked to write, in order. */
    val files: List<File> get() = opened
    fun open(file: File): OutputStream {
        opened.add(file)
        val real = FileOutputStream(file, append)
        return object : OutputStream() {
            override fun write(b: Int) { real.write(b); bytesWritten += 1 }
            override fun write(b: ByteArray, off: Int, len: Int) { real.write(b, off, len); bytesWritten += len.toLong() }
            override fun flush() { real.flush() }
            override fun close() { closes += 1; real.close() }
        }
    }
}

/** Where a [FailingOutput] fails. */
internal enum class OutputFault { WRITE, CLOSE }

/**
 * A real file whose write (past [failAfterBytes]) or close throws [error]; [fileExistedWhenFailing]
 * says the partial file was on disk then, so a test can show it deleted something that was there.
 */
internal class FailingOutput(
    private val file: File,
    private val failAfterBytes: Int,
    private val fault: OutputFault,
    private val error: IOException = IOException("disk full"),
) : OutputStream() {
    private val real = FileOutputStream(file)

    @Volatile var written: Int = 0
    @Volatile var fileExistedWhenFailing: Boolean = false

    override fun write(b: Int) { write(byteArrayOf(b.toByte()), 0, 1) }
    override fun write(b: ByteArray, off: Int, len: Int) {
        if (fault == OutputFault.WRITE && written + len > failAfterBytes) {
            fileExistedWhenFailing = file.exists()
            throw error
        }
        real.write(b, off, len)
        written += len
    }

    override fun close() {
        real.close()
        if (fault == OutputFault.CLOSE) {
            fileExistedWhenFailing = file.exists()
            throw error
        }
    }
}

/** The fetcher through its internal constructor, every seam a fake unless a test passes its own. */
internal fun fetcherOf(
    opener: HttpOpener,
    limits: DownloadLimits = DownloadLimits(),
    cancelled: () -> Boolean = { false },
    clock: FakeClock = FakeClock(),
    openOutput: (File) -> OutputStream = { FileOutputStream(it) },
    usableSpace: (File) -> Long = { Long.MAX_VALUE },
): HttpModelFetcher = HttpModelFetcher(limits, cancelled, opener, { clock.now }, openOutput, usableSpace)

/** The outcome of one fetch call: a result, or the exception it threw. An Error is never caught here. */
internal class Attempt(val result: ModelFetcher.Result?, val thrown: Exception?) {
    private fun describe(claim: String, wanted: String): String =
        "$claim: expected $wanted but thrown=${thrown?.javaClass?.simpleName}:${thrown?.message} result=$result"

    /** The reason of a Failed result; an AssertionError naming [claim] when the call threw or fetched. */
    fun failedReason(claim: String): String =
        (result as? ModelFetcher.Result.Failed)?.reason ?: throw AssertionError(describe(claim, "a Failed result"))

    /** The file of a Fetched result; an AssertionError naming [claim] otherwise. */
    fun fetchedFile(claim: String): File =
        (result as? ModelFetcher.Result.Fetched)?.file ?: throw AssertionError(describe(claim, "a Fetched result"))

    /** The IOException that was thrown; an AssertionError naming [claim] when none was. */
    fun thrownIo(claim: String): IOException = (thrown as? IOException) ?: throw AssertionError(describe(claim, "a thrown IOException"))
}

internal fun attemptModel(fetcher: ModelFetcher, entry: ModelEntry, stagingDir: File): Attempt =
    try { Attempt(fetcher.fetchModel(entry, stagingDir), null) } catch (e: Exception) { Attempt(null, e) }

internal fun attemptChecksums(fetcher: ModelFetcher, stagingDir: File): Attempt =
    try { Attempt(fetcher.fetchChecksums(stagingDir), null) } catch (e: Exception) { Attempt(null, e) }
